---
- name: create system accounts and common prerequisities.
  hosts: azurefire
  vars_files:
  - vars.yml
  tasks:

  - name: install all of my public keys
    authorized_key: user=root state=present key=https://github.com/smashwilson.keys

  - name: update the apt cache and any installed packages
    apt: update_cache=yes upgrade=dist

  - name: set the timezone
    command: /bin/cp /usr/share/zoneinfo/America/New_York /etc/localtime
