---
- name: build azurefire
  hosts: azurefire
  vars_files:
  - vars.yml
  - ["credentials.yml", "credentials.vault.yml"]
  tasks:

  - name: site build
    docker:
      name: azurefire
      image: quay.io/smashwilson/azurefire
      state: started
      detach: no
      env:
        RACKSPACE_USERNAME: "{{ rackspace_username }}"
        RACKSPACE_APIKEY: "{{ rackspace_api_key }}"
        RACKSPACE_REGION: "{{ rackspace_region }}"
        RACKSPACE_CONTAINER: "{{ asset_container }}"
