---
- name: build azurefire
  hosts: azurefire
  tasks:

  - name: site build
    docker:
      name: azurefire
      image: quay.io/smashwilson/azurefire
      state: started
      env:
        RACKSPACE_USERNAME: "{{ rackspace_username }}"
        RACKSPACE_APIKEY: "{{ rackspace_apikey }}"
        RACKSPACE_REGION: "{{ rackspace_region }}"
        RACKSPACE_CONTAINER: "{{ asset_container }}"
