---
- name: nginx
  hosts: azurefire
  vars_files:
  - vars.yml
  - ["credentials.yml", "credentials.vault.yml"]
  tasks:

  - name: host directories
    file: dest=/var/nginx/ssl state=directory

  - name: install the SSL certificate
    copy:
      src: files/certificates/azurefire.net.crt
      dest: /var/nginx/ssl/azurefire.net.crt
      mode: "0644"
    notify:
    - restart nginx

  - name: install the private key
    template:
      src: templates/azurefire.net.key.j2
      dest: /var/nginx/ssl/azurefire.net.key
      mode: "0600"
    notify:
    - restart nginx

  - name: install the nginx configuration
    template:
      src: templates/nginx.conf.j2
      dest: /var/nginx/nginx.conf
      mode: "0600"
    notify:
    - restart nginx

  - name: nginx:1.7
    docker:
      name: nginx
      image: nginx
      state: reloaded
      ports:
      - "80:80"
      - "443:443"
      volumes:
      - "/var/nginx/ssl:/var/ssl:ro"
      - "/var/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      volumes_from:
      - azurefire
      restart_policy: always

  handlers:

  - name: restart nginx
    docker: name=nginx image=nginx state=restarted
