---
- name: pushbot
  hosts: azurefire
  vars_files:
  - vars.yml
  - ["crendentials.yml", "credentials.vault.yml"]
  tasks:

  - name: redis data container
    docker:
      image: alpine:3.1
      name: data-redis
      state: present
      volumes:
      - /data
    tags:
    - pushbot
    - heatlamp

  - name: redis
    docker:
      image: redis:2.8.19
      command: redis-server --appendonly yes
      name: redis
      state: started
      volumes_from:
      - data-redis
      restart_policy: always
    tags:
    - pushbot
    - heatlamp

  - name: pushbot
    docker:
      pull: always
      image: smashwilson/pushbot
      name: pushbot
      state: reloaded
      links:
      - "redis:redis"
      volumes:
      - "/usr/src/app/botdata:/var/pushbot/botdata"
      env:
        REDISTOGO_URL: redis://redis/
        HUBOT_SLACK_TOKEN: "{{ pushbot_slack_token }}"
        HUBOT_MARKOV_LEARN_MIN: 2
        HUBOT_MARKOV_GENERATE_MAX: 100
        HUBOT_GREETINGS_FFA: 1
        HUBOT_QUOTEFILE_PATH: botdata/quotes
        HUBOT_AUTH_ADMIN: U02D23B7J,U02D23G6N
        HUBOT_BETRAY_IMMUNE: U02D23B7J,U02D23G6N,U02D25HJG,U02D1CX67
        HUBOT_WEATHER_APIKEY: "{{ pushbot_weather_apikey }}"
      restart_policy: always
    tags:
    - pushbot
    - heatlamp
