---
- name: pushbot
  hosts: azurefire
  vars_files:
  - vars.yml
  - ["credentials.yml", "credentials.vault.yml"]
  tasks:

  - name: pushbot data directory
    file: path=/var/pushbot/botdata state=directory

  - name: redis data container
    docker:
      name: redis-data
      image: alpine
      state: present
      volumes:
      - /data

  - name: redis:2.8
    docker:
      name: redis
      image: redis
      command: redis-server --appendonly yes
      state: reloaded
      volumes_from: redis-data
      restart_policy: always

  - name: redis-cli
    copy: src=files/redis-cli dest=/usr/local/bin/redis-cli mode=0755

  - name: pushbot
    docker:
      name: pushbot
      image: quay.io/smashwilson/pushbot
      state: reloaded
      pull: always
      links:
      - "redis:redis"
      volumes:
      - "/usr/src/app/botdata:/var/pushbot/botdata"
      env:
        HUBOT_SLACK_TOKEN: "{{ pushbot_slack_token }}"
        HUBOT_MARKOV_LEARN_MIN: "2"
        HUBOT_MARKOV_GENERATE_MAX: "100"
        HUBOT_GREETINGS_FFA: "1"
        HUBOT_QUOTEFILE_PATH: /usr/src/app/botdata
        HUBOT_AUTH_ADMIN: "U02D23B7J,U02D23G6N"
        HUBOT_BETRAY_IMMUNE: "U02D23B7J,U02D23G6N,U02D25HJG,U02D1CX67"
        HUBOT_WEATHER_APIKEY: "{{ pushbot_weather_apikey }}"
      restart_policy: always
